### ISSUE TITLE
how to stop without any pod not deleted

### ISSUE THREAD

**Issue by wgtgithub** [scholzj/aws-k8s-kops-ansible#12]
Hi, Jakub

I would like to stoping K8S temporaly.
But any pods were deleted after stoped K8S, you know.
Do you have any idea for keeping node at stop K8S?

best regards,

**Comment by scholzj** [comment]
If I understand you correctly ... you would like to stop your cluster with running pods ... and have the pods start automatically again when you start the cluster again?

**Comment by wgtgithub** [comment]
Yes, correct.
I would like to know way to restart pods automatically with cluster restart.
kops deletes all of deployed images, maybe...right?

**Comment by scholzj** [comment]
`Kops` use auto-scaling groups to control the hosts. If you edit them manually and set the "desired / min / max" numbers to 0, they will shutdown all the hosts. The data about the deployments are stored on EBS volumes which will continue to exist. So they will not be lost.

Later you can edit the autoscaling groups again and return the "desired / min / max" numbers to the original values. This will start the nodes again. Once the masters and nodes are started they will automatically see the deployments and start the Pods. I just gave it a try and it seems to work - so if this doesn't work for you I would be interested to know more details about your configuration.

*Just for the record - the Pod it self is non-recoverable. You always need to use some higher level record such as Deployment, Replication Controller or StateFul set to recover from the cluster shutdown. If you create Pods directly, they will never recover from such event.*

**Comment by scholzj** [comment]
@wgtgithub Dir my response helped you in any way? Or do you still have some problems?

**Comment by scholzj** [comment]
I will close this since I got no response since one week. Feel free to reopen it or open a new issue if you still have some issues.
