### ISSUE TITLE
How can I import docker image file to K8S

### ISSUE THREAD

**Issue by wgtgithub** [scholzj/aws-k8s-kops-ansible#13]
Usually we can do the following way,
`docker save <image>|ssh <node> import -`

But all of node does not reply after ping or ssh.
Is it different the way?
I used node name.
Is it right?

**Comment by scholzj** [comment]
This setup creates the nodes in private subnets - that means that you cannot SSH directly into them. It creates a *bastion* host which is accessible from outside with SSH and from where you can connect into the hosts. So what you would need to do is to copy it through the bastion host into the nodes. I'm sure it is possible to configure this in SSH but to be honest I'm not really expert on configuring the SSH daemons - perhaps [Google](https://www.google.com/search?q=ssh+tunnel+through+bastion+host&oq=ssh+tunnel+through+bastion+host&aqs=chrome..69i57j0.8391j0j7&sourceid=chrome&ie=UTF-8) can help.

Other option is to use some Docker registry. If your docker images are not secret, maybe you can just upload them to Docker Hub. If they are secret, you migth give a try to some private Docker registry such as the one provided by [Kubernetes](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry) (for the record, I don't have much experience with this)

**Comment by wgtgithub** [comment]
I have done it.
First of all imported docker image into amazon ecr.
and next, deployed a pod from ecr, the following command
`kubectl run <podname> -n default --image <accountnum>.dkr.ecr.<myregion>.amazonaws.com/<myrepository>:latest --command tailf /dev/null`

Maybe, if you know:)

**Comment by scholzj** [comment]
Yeah, using the ECR Docker registry i also an option which should work.

**Comment by scholzj** [comment]
@wgtgithub I assume I can close this issue now. If you have some further questions with regards to this feel free to reopen it or start a new one.
