### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by akgerber** [scholzj/aws-k8s-kops-ansible#14]
Thanks for sharing this useful repo! It's worked great for launching a Kubernetes cluster for me.

May I request you choose an open source license for it?
https://github.com/blog/1530-choosing-an-open-source-license

**Comment by scholzj** [comment]
Good point - I'm not sure why the license was missing. Thansk for pointing this out. I hope Apache License 2.0 will work for you.

**Comment by akgerber** [comment]
Works perfectly. Thanks much.
