### ISSUE TITLE
Is the default CIDR block usable?

### ISSUE THREAD

**Issue by akgerber** [scholzj/aws-k8s-kops-ansible#15]
Unless I'm mistaken, per http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html#VPC_Sizing,
172.35.0.0/16 is not an allocatable private CIDR block.

**Comment by scholzj** [comment]
I actually use 172.35.0.0/16 from time to time and it seems to work fine. Maybe there are problems only when you get into conflict with some specific service or something like that. Anyway, I'm going to change the defaults to 172.16.0.0/16 which should be valid.
